# This file was generated by GoReleaser. DO NOT EDIT.
cask "devm" do
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-rd", "com.apple.quarantine", staged_path]
    # If the devm service is installed, restart it so it picks up
    # this newly-installed binary. Best-effort — silent when the
    # service isn't registered (a fresh install) or isn't running.
    system_command "#{HOMEBREW_PREFIX}/bin/devm",
                   args: ["restart"],
                   must_succeed: false
  end

  version "0.7.2"

  on_macos do
    on_arm do
      sha256 "2b1083661a56fab8f066f82ec9b64613175a7af69c754ea36c633a3f25a6a9df"
      url "https://github.com/mdubb86/devm/releases/download/v#{version}/devm_v#{version}_darwin_arm64.tar.gz"
    end
  end

  name "devm"
  desc "Mac dev sandbox tool (wraps Tart VMs + iron-proxy egress enforcement)"
  homepage "https://github.com/mdubb86/devm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devm"

  # No zap stanza required

end
