# This file was generated by GoReleaser. DO NOT EDIT.
cask "devm" do
  no_quarantine

  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "db9016a3028de05b979d7656716c7e777b0058cfedab353bd532c0b2ed9b7df5"
      url "https://github.com/mdubb86/devm/releases/download/v#{version}/devm_v#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9f932d3939ab52f85ada251ef9dda3c3008633b35fbd2b518fa1cefb811c733f"
      url "https://github.com/mdubb86/devm/releases/download/v#{version}/devm_v#{version}_darwin_arm64.tar.gz"
    end
  end

  name "devm"
  desc "Mac dev sandbox tool (wraps Docker Sandboxes)"
  homepage "https://github.com/mdubb86/devm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "devm"

  # No zap stanza required

end
