# This file was generated by GoReleaser. DO NOT EDIT.
cask "localias" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "861aaac4c1b31ef5b72c3665ee23ae834425fbbce7be4727a902797831dd89a7"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "fcb292b21a2a227f0041f3d5044ad8a18b21dddaed0e6a3c59e76af0c6e864ef"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "47819e324e72174e0182ce7ef23f0cf6cd7f16a37fb6d2cc00b48102ec7c9b9c"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b269849da3996c4d87b22a10aa7eee4bf0caa4599a32a98e232821800052b357"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_linux_arm64.tar.gz"
    end
  end

  name "localias"
  desc "Manage local hosts-file aliases via a background daemon"
  homepage "https://github.com/mdubb86/localias"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localias"

  # No zap stanza required

end
