# This file was generated by GoReleaser. DO NOT EDIT.
cask "localias" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "9ed3fbeb95d1ef0f73a7aa0d68c74d9b5896dbc8ab14b43fa221c03c13306fd7"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e8c732af79ae6effe839bfd4a2184c2725e19cb72bbce2e18085cc34ce3c267b"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ba363f5b0ecb426be01d1f92a0cc702de7363a6338be6149ece7d110e2f67185"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a76c571b9ecf68d703b6d81c73c81da476f3c2fb06c4500ca12bd23160ab69b7"
      url "https://github.com/mdubb86/localias/releases/download/v#{version}/localias_linux_arm64.tar.gz"
    end
  end

  name "localias"
  desc "Manage local hosts-file aliases via a background daemon"
  homepage "https://github.com/mdubb86/localias"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "localias"

  # No zap stanza required

end
